version: '3.8'

x-common-variables: &common-variables
  MYSQL_HOST: ${MYSQL_HOST:-localhost}
  MYSQL_DATABASE: ${MYSQL_DATABASE:-fullstackform_db}
  MYSQL_USER: ${MYSQL_USER:-root}
  MYSQL_PASSWORD: ${MYSQL_PASSWORD:-Fullstackform1985}
  MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-Fullstackform1985}

x-fastapi-variables: &fastapi-variables
  <<: *common-variables
  PORT: ${PORT:-8000}
  ADMIN_EMAIL: ${ADMIN_EMAIL:-loise.fenoll@ynov.com}
  ADMIN_PASSWORD: ${ADMIN_PASSWORD:-PvdrTAzTeR247sDnAZBr}

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-fullstackform_db}
      MYSQL_USER: ${MYSQL_USER:-root}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-Fullstackform1985}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-Fullstackform1985}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sqlfiles:/docker-entrypoint-initdb.d
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - mysql

  server:
    build: ./server
    container_name: fastapi_backend
    restart: always
    env_file:
      - .env
    environment:
      <<: *fastapi-variables
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      ENVIRONMENT: production
    ports:
      - "8000:8000"
    networks:
      - app-network
    volumes:
      - ./server:/app
    depends_on:
      - mysql

  client:
    build:
      context: .
      dockerfile: DockerfileReact
    container_name: react_frontend
    restart: always
    ports:
      - "3000:80"
    environment:
      - VITE_REACT_APP_API_URL=http://localhost:8000
      - VITE_BASE_PATH=/
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - server
    networks:
      - app-network
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - /app/node_modules

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
